#index:
#    path: /
#    controller: App\Controller\DefaultController::index

srp_page:
  path: /
  controller: App\Controller\SRPController::go

get_all_inventory:
  path: /get/all_inventory
  controller: App\Controller\SRPController::GetAllInventory

get_filtered_inventory:
  path: /get/filter
  controller: App\Controller\SRPController::filterController

get_max_price:
  path: /get/max_price
  controller: App\Controller\SRPController::getMaxPrice

get_max_year:
  path: /get/max_year
  controller: App\Controller\SRPController::getMaxYear

get_all_body:
  path: /get/all_body_types
  controller: App\Controller\SRPController::getAllBodyTypes